### ISSUE TITLE
I thought this was funny

### ISSUE THREAD

**Issue by monlouisj** [hungtraan/FacebookBot#8]
Good morning Jeffrey 😀
How can I help you?
How much is an iPhone7 at bestbuy.com ?

6 dollars and 14 cents .

**Comment by hungtraan** [comment]
Haha I got "It's a priceless but buttless creation"! omg

**Comment by monlouisj** [comment]
For my own understanding, is there a magic command that could make intelligible and give me a log of how the bot chose to answer "$6.14 cts" ?

**Comment by hungtraan** [comment]
What I am actually doing right now is logging all the responses into my own database by using a third-party Machine Learning chat service. I mentioned that in my document, it's Simsimi over here: developer.simsimi.com/apps

Obviously the bot without any knowledge of how to response would be pretty awkward, so I plan to use the collected responses and chat to try implementing my own chat algorithm.

A good reference is [Chatterbot](https://github.com/gunthercox/ChatterBot) project here, and the gist of their response algorithm is calculating "distance" from a query to responses and choose the optimal one. You can find example algorithms that Chatterbot has implemented in this folder: https://github.com/gunthercox/ChatterBot/tree/master/chatterbot/adapters/logic

Hope this helps :)

**Comment by monlouisj** [comment]
OK thank you for the tips!
