### ISSUE TITLE
use case for natural language processing

### ISSUE THREAD

**Issue by steve21124** [hungtraan/FacebookBot#9]
Android has : https://developer.android.com/reference/android/speech/SpeechRecognizer.html and apple has sirikit for ios 10. Is there still a need to use ibm watson for natural language?

**Comment by hungtraan** [comment]
Hi Steve,

I think you meant the voice recognition speech-to-text? You're right, if the user leverages the OS-provided speech to text capability, it will appear as if s/he has typed the message out, so that would mean there's no need for IBM Watson voice recognition.

**Comment by macbroadcast** [comment]
Hello @hungtraan , i think  @steve21124  means when you have  speech recognizer for android and Sirikit for IOS, why you need IBM watson , but believe you just wanted one code base for both plattforms thats why you choosed IBM correct ? :smile:

**Comment by steve21124** [comment]
Thanks for info
